stages:
  - install
  - test
  - build
  - deploy

install:
  stage: install
  image: node:16
  script:
    - npm install

test:
  stage: test
  image: node:16
  script:
    - npm test

build:
  stage: build
  image: node:16
  script:
    - npm run build

deploy:
  stage: deploy
  image: node:16
  script:
    - ./deploy.sh
  only:
    - main
